# Generated by Django 4.1.3 on 2023-05-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='quantuty',
            field=models.IntegerField(default=1),
        ),
    ]
