# Generated by Django 4.1.3 on 2023-06-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_product_add_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='add_to_cart',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Add_product',
        ),
        migrations.DeleteModel(
            name='Add_to_cart',
        ),
    ]
