# Generated by Django 4.1.3 on 2023-06-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_add_to_cart_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=30)),
                ('quantuty', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.maincatagory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
