# Generated by Django 4.1.3 on 2023-06-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phon',
            field=models.IntegerField(default=91),
        ),
    ]
