# Generated by Django 4.1.3 on 2023-06-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_address_phon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
