# Generated by Django 4.1.3 on 2023-06-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('Saddress', models.CharField(max_length=500)),
                ('Aaddress', models.CharField(max_length=500)),
                ('town_city', models.CharField(max_length=500)),
                ('Country_State', models.CharField(max_length=200)),
                ('phon', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
